# Generated by Django 3.2.3 on 2021-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='birth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='e_email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='name_lastname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
