# Generated by Django 3.2.3 on 2021-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20210531_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='birth',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='e_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name_lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='website',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
