# Generated by Django 3.2.3 on 2021-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_auto_20210531_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='address',
        ),
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='birth',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='e_email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='name_lastname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='website',
            field=models.CharField(max_length=150),
        ),
    ]
