# Generated by Django 3.2.3 on 2021-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_auto_20210531_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
