# Generated by Django 3.2.3 on 2021-05-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_info_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='address',
            new_name='addres',
        ),
    ]
