# Generated by Django 3.2.3 on 2021-05-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_rename_address_info_addres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='addres',
        ),
    ]
