# Generated by Django 3.2.3 on 2021-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
